// AI 홈(/)과 티미 대화(/chat) 화면 문구. 한/영을 항상 함께 고친다.
export const aiHomeCopy = {
  ko: {
    langToggle: 'EN',
    langToggleLabel: 'Switch to English',
    notifications: '알림',
    login: '로그인',

    heroTitle: ['혼자 떠나도', '든든하게'],
    heroBody: '어디로 갈지 말해 주세요. 일정부터 숙소 동네, 밤 이동까지 티미가 함께 챙겨요.',
    suggestions: [
      { label: '혼자 가는 첫 유럽', prompt: '혼자 가는 첫 유럽 여행이에요. 일정 짜는 것부터 도와줘.' },
      { label: '방콕 4박, 밤에 도착해요', prompt: '방콕 4박 여행인데 밤 늦게 도착해요. 공항에서 숙소까지 안전하게 가는 방법과 일정 추천해줘.' },
      { label: '치안 좋은 숙소 동네', prompt: '혼자 묵기 좋은, 밤에도 안전한 숙소 동네를 고르는 방법을 알려줘.' },
      { label: '친구랑 오사카 맛집', prompt: '친구랑 오사카 3박 4일, 맛집 위주로 일정 짜줘.' },
    ],
    safetyTitle: '안심 기능 미리 켜 두기',
    safetyBody: '비상 연락처 등록 · 안심 귀가 타이머 · 보호자에게 위치 보내기',
    safetyCta: '1분이면 끝나요',
    shortcuts: {
      flights: ['항공권', '최저가'],
      stay: ['안심 숙소', '동네'],
      stayPrompt: '혼자 여행할 때 안전한 숙소 동네를 고르는 기준과 추천을 알려줘. 목적지는 아직 안 정했어.',
      planner: ['일정표', '직접 만들기'],
    },

    upcoming: '다가오는 여행',
    viewItinerary: '일정표 보기',
    readinessTitle: '안심 준비',
    readiness: [
      { id: 'passport', label: '여권 유효기간 확인' },
      { id: 'address', label: '숙소 주소 현지어로 저장' },
      { id: 'guardian', label: '비상 연락처 등록하기', action: 'safe' },
      { id: 'emergency', label: '현지 긴급번호·영사콜센터 저장' },
    ],
    flightsRow: '항공권 최저가 비교',
    askAboutTrip: (dest) => [
      { label: '숙소 주변, 밤에 걸어도 돼?', prompt: `${dest} 여행 중인데 숙소 주변을 밤에 혼자 걸어도 괜찮은지, 조심할 점 알려줘.` },
      { label: '소매치기 조심할 곳', prompt: `${dest}에서 소매치기나 사기를 조심해야 할 곳과 대처법 알려줘.` },
    ],

    onTripLabel: (n) => `여행 중 · ${n}일차`,
    safeModeButton: '안전모드',
    safeActive: '안전모드 켜짐 · 안심 귀가 보호 중',
    safeManage: '관리',
    today: '오늘',
    nextPlace: '다음 장소',
    directions: '길찾기',
    markDone: '다녀왔어요',
    markUndone: '다녀온 표시 지우기',
    noPlacesToday: '오늘은 정해진 일정이 없어요. 티미에게 근처 갈 만한 곳을 물어보세요.',
    fullItinerary: '전체 일정 보기',
    quick: {
      safeReturn: '안심 귀가',
      safeReturnSub: '귀가 타이머·보호자 알림',
      translate: '메뉴판 번역',
      around: '내 주변',
      diary: '오늘 일기',
    },

    composerLabel: '티미에게 메시지',
    composerPlaceholder: '여행지, 날짜, 누구와… 편하게 말해요',
    composerPlaceholderTrip: (dest) => `${dest} 여행, 무엇이든 물어보세요`,
    composerPlaceholderOnTrip: '근처에 늦게까지 여는 약국?',
    send: '보내기',
    mic: '음성으로 말하기',
    micListening: '듣고 있어요…',
    micUnsupported: '이 기기에서는 음성 입력을 쓸 수 없어요. 키보드의 마이크 버튼을 써 주세요.',

    nav: { home: '홈', trips: '내 일정', map: '지도', safety: '안심', my: '마이' },
    footerGuide: '사용 가이드',
    footerPrivacy: '개인정보처리방침',

    chatTitle: '티미',
    chatSubtitle: 'AI 여행 동반자',
    back: '홈으로',
    newChat: '새 대화',
    chatWelcome: '안녕하세요, 티미예요. 어디로, 언제, 누구와 떠나는지 알려 주시면 일정과 숙소 동네, 이동 방법까지 함께 정리해 드릴게요.',
    chatThinking: '티미가 생각하고 있어요',
    makeItinerary: '이 내용으로 일정표 만들기',
    chatDisclaimer: '영업시간·가격은 바뀔 수 있어요. 예약 전 꼭 확인하세요.',
    attachPhoto: '사진 번역',
    loginForMemory: '로그인하면 티미가 취향을 기억하고 대화가 저장돼요.',
  },
  en: {
    langToggle: '한국어',
    langToggleLabel: '한국어로 보기',
    notifications: 'Notifications',
    login: 'Log in',

    heroTitle: ['Travel solo,', 'travel sure'],
    heroBody: 'Tell me where you want to go. Timmy helps with the plan, the right neighborhood to stay in, and getting around after dark.',
    suggestions: [
      { label: 'My first solo trip to Europe', prompt: "It's my first solo trip to Europe. Help me start planning." },
      { label: 'Bangkok, landing late', prompt: "I'm going to Bangkok for 4 nights and landing late at night. How do I get from the airport to my hotel safely, and what should I plan?" },
      { label: 'Safe areas to stay', prompt: 'How do I pick a neighborhood that is safe to stay in alone, even at night?' },
      { label: 'Osaka food trip', prompt: 'Plan a 4-day Osaka trip with a friend, focused on food.' },
    ],
    safetyTitle: 'Set up safety features first',
    safetyBody: 'Emergency contact · Safe-return timer · Send your location to a guardian',
    safetyCta: 'Takes a minute',
    shortcuts: {
      flights: ['Cheapest', 'flights'],
      stay: ['Safe areas', 'to stay'],
      stayPrompt: "What should I look for in a safe neighborhood to stay in when traveling solo? I haven't picked a destination yet.",
      planner: ['Build an', 'itinerary'],
    },

    upcoming: 'Upcoming trip',
    viewItinerary: 'View itinerary',
    readinessTitle: 'Safety checklist',
    readiness: [
      { id: 'passport', label: 'Check passport expiry' },
      { id: 'address', label: 'Save hotel address in the local language' },
      { id: 'guardian', label: 'Add an emergency contact', action: 'safe' },
      { id: 'emergency', label: 'Save local emergency numbers' },
    ],
    flightsRow: 'Compare flight prices',
    askAboutTrip: (dest) => [
      { label: 'Is my area safe at night?', prompt: `I'm traveling in ${dest}. Is it OK to walk around my hotel area alone at night? What should I watch out for?` },
      { label: 'Pickpocket hotspots', prompt: `Where should I watch out for pickpockets and scams in ${dest}, and what should I do?` },
    ],

    onTripLabel: (n) => `On the trip · Day ${n}`,
    safeModeButton: 'Safe Mode',
    safeActive: 'Safe Mode on · Safe-return protection active',
    safeManage: 'Manage',
    today: 'Today',
    nextPlace: 'Next stop',
    directions: 'Directions',
    markDone: 'Mark as visited',
    markUndone: 'Unmark visited',
    noPlacesToday: 'Nothing planned today. Ask Timmy what is worth seeing nearby.',
    fullItinerary: 'Full itinerary',
    quick: {
      safeReturn: 'Safe return',
      safeReturnSub: 'Timer & guardian alert',
      translate: 'Translate a menu',
      around: 'Around me',
      diary: 'Today’s diary',
    },

    composerLabel: 'Message Timmy',
    composerPlaceholder: 'Where, when, who with… just say it',
    composerPlaceholderTrip: (dest) => `Ask anything about ${dest}`,
    composerPlaceholderOnTrip: 'Any pharmacy open late nearby?',
    send: 'Send',
    mic: 'Speak',
    micListening: 'Listening…',
    micUnsupported: "Voice input isn't available on this device. Try the mic on your keyboard.",

    nav: { home: 'Home', trips: 'Trips', map: 'Map', safety: 'Safety', my: 'Me' },
    footerGuide: 'How it works',
    footerPrivacy: 'Privacy Policy',

    chatTitle: 'Timmy',
    chatSubtitle: 'AI travel companion',
    back: 'Back to home',
    newChat: 'New chat',
    chatWelcome: "Hi, I'm Timmy. Tell me where, when and who you're traveling with, and I'll help with the plan, where to stay and how to get around.",
    chatThinking: 'Timmy is thinking',
    makeItinerary: 'Turn this into an itinerary',
    chatDisclaimer: 'Opening hours and prices change. Double-check before you book.',
    attachPhoto: 'Translate a photo',
    loginForMemory: 'Log in so Timmy remembers your preferences and saves your chats.',
  },
};

export const getAiHomeCopy = (language) => aiHomeCopy[language] || aiHomeCopy.ko;
