// 일정 상세 화면(components/trip) 문구. 한/영을 항상 함께 고친다.
export const tripCopy = {
  ko: {
    back: '뒤로',
    share: '공유',
    more: '더 보기',
    dayLabel: (n) => `${n}일차`,
    tabs: { plan: '일정', stay: '숙소', safety: '안심·팁', budget: '경비' },
    nearby: { restaurant: '맛집', cafe: '카페', attraction: '볼거리', essentials: '편의점·약국' },
    nearbyAdd: '일정에 추가',
    nearbyEmpty: '주변에서 찾지 못했어요',
    myLocation: '내 위치',
    modes: { WALKING: '도보', TRANSIT: '대중교통', DRIVING: '차' },
    modeGroup: '이동 수단',
    minutes: (n) => `${n}분`,
    daySummary: (count, minutes, mode) => `${count}곳${minutes ? ` · 이동 약 ${minutes}분` : ''} · ${mode} 위주`,
    places: (n) => `${n}곳`,
    noPlaces: '이 날은 아직 일정이 없어요.',
    mapView: '지도로 보기',
    nightReturn: '밤 일정이에요. 숙소까지는 밝은 큰길로 이동하세요.',
    safePoint: '안심 포인트',
    directions: '길찾기',
    prev: '이전 장소',
    next: '다음 장소',
    reviews: '리뷰·사진 보기',
    swap: '비슷한 곳으로 바꾸기',
    remove: '빼기',
    removeConfirm: (name) => `‘${name}’을(를) 일정에서 뺄까요?`,
    placeOf: (day, n) => `${day}일차 · ${n}번째 장소`,
    save: '이 일정 저장하기',
    saved: '저장된 일정',
    saveCopy: '내 일정으로 저장하기',
    edit: '편집',
    invite: '동행 초대',
    inviteCopied: '초대 링크를 복사했어요. 함께 갈 사람에게 보내 주세요.',
    // 저장 확인
    saveTitle: '일정을 저장할까요?',
    saveBody: '저장하면 홈에서 출발 전 준비와 여행 중 오늘 일정을 바로 볼 수 있어요.',
    shareToFeed: '여행자 피드에도 공유하기',
    shareToFeedHint: '날짜·숙소 동네가 다른 회원에게 보여요. 혼자 여행이라면 여행이 끝난 뒤 공유하는 걸 권해요.',
    saveConfirm: '저장하기',
    cancel: '취소',
    saving: '저장하는 중…',
    savedToast: '일정을 저장했어요',
    welcomeToast: '가입 축하 1,000P와 함께 일정을 저장했어요',
    saveError: '저장하지 못했어요. 잠시 후 다시 시도해 주세요.',
    loginNeeded: '저장하려면 구글로 로그인해 주세요.',
    // 더 보기
    menu: { copyText: '일정 글로 복사', print: 'PDF로 저장(인쇄)', consult: '카톡으로 여행 상담', chat: '동행 채팅', invite: '동행 초대 링크 복사' },
    shareCopied: '공유 링크를 복사했어요',
    textCopied: '일정을 복사했어요',
    // 숙소
    stayAreaTitle: '추천 숙소 동네',
    stayCompare: '가격 비교하기',
    stayMap: '지도',
    stayNote: '안심 점수와 가격은 AI가 공개 정보를 바탕으로 추정한 값이에요. 예약 전 최근 후기와 위치를 꼭 확인하세요.',
    stayEmpty: '추천 숙소 정보가 없어요.',
    safetyBadge: (s) => `안심 ${s}`,
    mainStreet: '큰길가',
    soloFriendly: '혼자 묵기 좋음',
    // 안심·팁
    police: '경찰',
    ambulance: '구급·소방',
    touristPolice: '관광경찰',
    consular: '영사콜센터',
    emergencyUnknown: '현지 긴급번호는 출발 전에 꼭 확인해 두세요.',
    safeModeTitle: '밤에 이동할 땐 안전모드',
    safeModeSub: '귀가 타이머 · 보호자에게 위치 보내기',
    safetyTitle: '이 여행의 안심 포인트',
    weather: '날씨',
    tips: '여행 팁',
    // 경비
    budgetTotal: '예상 경비',
    budgetItems: '항목별 예상',
    budgetPlaces: '장소별 예상 비용',
    budgetTrack: '여행 중 실제 지출은 트립머니에 기록하세요',
    budgetTrackCta: '트립머니 열기',
    budgetEmpty: '예상 경비 정보가 없어요.',
    // 편집
    editTitle: (n) => `${n}일차 편집`,
    done: '완료',
    editHint: '손잡이를 끌어 순서를 바꾸면 이동 시간이 다시 계산돼요.',
    dragHandle: (name) => `${name} 순서 바꾸기`,
    removeAria: (name) => `${name} 빼기`,
    moveUp: '위로',
    moveDown: '아래로',
    addHere: '여기에 장소 추가',
    optimize: 'AI가 이동 동선 다시 짜기',
    optimized: '가까운 순서로 동선을 다시 짰어요',
    askLabel: '말로 부탁해도 돼요',
    askPlaceholder: '4번 대신 조용한 저녁 식당 넣어 줘',
    asking: '티미가 일정을 고치고 있어요…',
    askDone: '요청대로 고쳤어요',
    askError: '고치지 못했어요. 다르게 말해 주세요.',
    // 장소 추가
    addTitle: '장소 추가',
    addSearch: '장소 이름으로 찾기',
    addSearchPlaceholder: '예: 니시키 시장',
    addAi: 'AI 추천으로 추가',
    addAiCats: ['맛집', '카페', '볼거리', '쇼핑'],
    adding: '찾는 중…',
    addNoResult: '검색 결과가 없어요.',
    added: (name) => `‘${name}’을(를) 추가했어요`,
    close: '닫기',
    swapping: '비슷한 곳을 찾는 중…',
    swapped: (name) => `‘${name}’(으)로 바꿨어요`,
    mapLoading: '지도를 불러오는 중…',
    readOnly: '공유받은 일정이에요',
  },
  en: {
    back: 'Back',
    share: 'Share',
    more: 'More',
    dayLabel: (n) => `Day ${n}`,
    tabs: { plan: 'Plan', stay: 'Stay', safety: 'Safety', budget: 'Budget' },
    nearby: { restaurant: 'Food', cafe: 'Cafés', attraction: 'Sights', essentials: 'Pharmacy' },
    nearbyAdd: 'Add to plan',
    nearbyEmpty: 'Nothing found nearby',
    myLocation: 'My location',
    modes: { WALKING: 'Walk', TRANSIT: 'Transit', DRIVING: 'Car' },
    modeGroup: 'Travel mode',
    minutes: (n) => `${n} min`,
    daySummary: (count, minutes, mode) => `${count} stops${minutes ? ` · ~${minutes} min moving` : ''} · mostly ${mode.toLowerCase()}`,
    places: (n) => `${n} stops`,
    noPlaces: 'Nothing planned for this day yet.',
    mapView: 'Map view',
    nightReturn: 'Evening stop. Head back to your hotel along bright main roads.',
    safePoint: 'Safety note',
    directions: 'Directions',
    prev: 'Previous stop',
    next: 'Next stop',
    reviews: 'Reviews & photos',
    swap: 'Swap for something similar',
    remove: 'Remove',
    removeConfirm: (name) => `Remove “${name}” from the plan?`,
    placeOf: (day, n) => `Day ${day} · stop ${n}`,
    save: 'Save this itinerary',
    saved: 'Saved',
    saveCopy: 'Save to my trips',
    edit: 'Edit',
    invite: 'Invite',
    inviteCopied: 'Invite link copied. Send it to your travel buddy.',
    saveTitle: 'Save this itinerary?',
    saveBody: 'Once saved, your home screen shows the countdown before you go and today’s plan while you travel.',
    shareToFeed: 'Also share to the traveler feed',
    shareToFeedHint: 'Other members will see your dates and area. If you travel solo, consider sharing after the trip.',
    saveConfirm: 'Save',
    cancel: 'Cancel',
    saving: 'Saving…',
    savedToast: 'Itinerary saved',
    welcomeToast: 'Saved — plus a 1,000P welcome gift',
    saveError: 'Couldn’t save. Please try again.',
    loginNeeded: 'Log in with Google to save.',
    menu: { copyText: 'Copy as text', print: 'Save as PDF (print)', consult: 'Chat with us on Kakao', chat: 'Group chat', invite: 'Copy invite link' },
    shareCopied: 'Share link copied',
    textCopied: 'Itinerary copied',
    stayAreaTitle: 'Best area to stay',
    stayCompare: 'Compare prices',
    stayMap: 'Map',
    stayNote: 'Safety scores and prices are AI estimates from public info. Check recent reviews and the location before booking.',
    stayEmpty: 'No stay suggestions.',
    safetyBadge: (s) => `Safety ${s}`,
    mainStreet: 'Main street',
    soloFriendly: 'Solo-friendly',
    police: 'Police',
    ambulance: 'Ambulance/Fire',
    touristPolice: 'Tourist police',
    consular: 'Korean consular line',
    emergencyUnknown: 'Look up the local emergency number before you go.',
    safeModeTitle: 'Use Safe Mode at night',
    safeModeSub: 'Return timer · Send location to a guardian',
    safetyTitle: 'Safety notes for this trip',
    weather: 'Weather',
    tips: 'Tips',
    budgetTotal: 'Estimated cost',
    budgetItems: 'By category',
    budgetPlaces: 'By place',
    budgetTrack: 'Track what you actually spend in Trip Money',
    budgetTrackCta: 'Open Trip Money',
    budgetEmpty: 'No budget info.',
    editTitle: (n) => `Edit day ${n}`,
    done: 'Done',
    editHint: 'Drag the handle to reorder. Travel times update automatically.',
    dragHandle: (name) => `Reorder ${name}`,
    removeAria: (name) => `Remove ${name}`,
    moveUp: 'Move up',
    moveDown: 'Move down',
    addHere: 'Add a place here',
    optimize: 'Let AI reorder for shorter routes',
    optimized: 'Reordered by distance',
    askLabel: 'Or just ask',
    askPlaceholder: 'Swap stop 4 for a quiet dinner spot',
    asking: 'Timmy is updating the plan…',
    askDone: 'Updated as requested',
    askError: 'Couldn’t do that. Try saying it differently.',
    addTitle: 'Add a place',
    addSearch: 'Search by name',
    addSearchPlaceholder: 'e.g. Nishiki Market',
    addAi: 'Add an AI pick',
    addAiCats: ['Food', 'Café', 'Sights', 'Shopping'],
    adding: 'Searching…',
    addNoResult: 'No results.',
    added: (name) => `Added “${name}”`,
    close: 'Close',
    swapping: 'Finding something similar…',
    swapped: (name) => `Swapped for “${name}”`,
    mapLoading: 'Loading map…',
    readOnly: 'Shared itinerary',
  },
};

export const getTripCopy = (language) => tripCopy[language] || tripCopy.ko;
