// 내 일정 목록(/trips, components/trips) 문구. 한/영을 항상 함께 고친다.
export const tripsCopy = {
  ko: {
    title: '내 일정',
    newTrip: '새 일정 만들기',
    tabsLabel: '일정 구분',
    tabUpcoming: (n) => `다가오는 여행 ${n}`,
    tabPast: (n) => `지난 여행 ${n}`,
    loading: '일정을 불러오는 중…',
    loginTitle: '로그인하면 저장한 일정이 여기에 모여요',
    loginBody: '일정은 로그인 없이도 만들 수 있어요. 저장할 때 로그인하면 돼요.',
    login: '로그인',

    invite: (name, dest) => `${name}님이 ‘${dest}’에 초대했어요`,
    inviteView: '보기',

    nearest: '가장 가까운 여행',
    undated: '날짜 미정',
    openTrip: '일정 열기',
    inviteCompanion: '동행 초대',
    more: (title) => `${title} 더 보기`,
    readiness: '안심 준비',
    nextTrips: '그다음 여행',
    otherTrips: '다른 일정',
    createWithTimmy: '티미와 새 일정 만들기',
    createWithTimmySub: '가고 싶은 곳만 말하면 일정 3개를 만들어요',

    onTrip: (n) => `지금 여행 중 · ${n}일차`,
    dayProgress: (n, total) => `${total}일 중 ${n}일차`,
    nextPlace: '다음 장소',
    noPlaceToday: '오늘 일정에 장소가 없어요',
    directions: (name) => `${name} 길찾기`,
    todayPlan: '오늘 일정 보기',
    safeMode: '안전모드',

    companions: { solo: '혼자', withN: (n) => `${n}명` },
    places: (n) => `장소 ${n}곳`,
    postTitle: (dest) => `${dest} 여행, 어떠셨어요?`,
    postBody: '사진 몇 장만 고르면 티미가 여행 일기로 정리해 드려요.',
    writeDiary: '여행 일기 쓰기',
    shareFeed: '피드에 공유하기',
    shareFeedDone: '피드에 공유했어요',
    postSafeNote: '여행이 끝났으니 이제 공유해도 안전해요.',
    reuse: '이 일정으로 다시 가기',
    pastEmpty: '아직 다녀온 여행이 없어요',
    upcomingEmpty: '다가오는 여행이 없어요',

    menu: {
      open: '지도와 일정 열기',
      rename: '이름 바꾸기',
      renameSave: '저장',
      renamePlaceholder: '일정 이름',
      invite: '동행 초대하기',
      inviteSub: '초대 링크를 보내면 같이 일정을 볼 수 있어요',
      shareLink: '공유 링크 만들기',
      shareLinkSub: '로그인 없이 일정만 볼 수 있어요',
      duplicate: '복사해서 새 일정 만들기',
      remove: '일정 삭제',
      leave: '이 일정에서 나가기',
      removeNote: '한 번 더 확인한 뒤 지워요.',
      leaveNote: '다른 동행의 일정은 그대로 남아요.',
      confirmRemove: (title) => `‘${title}’ 일정을 지울까요? 되돌릴 수 없어요.`,
      confirmLeave: (title) => `‘${title}’ 일정에서 나갈까요?`,
      confirmYes: '지우기',
      confirmLeaveYes: '나가기',
      cancel: '취소',
      close: '닫기',
    },
    toast: {
      renamed: '이름을 바꿨어요',
      linkCopied: '링크를 복사했어요',
      duplicated: '새 일정을 만들었어요',
      removed: '일정을 지웠어요',
      left: '일정에서 나왔어요',
      failed: '처리하지 못했어요. 잠시 후 다시 시도해 주세요',
    },
    copySuffix: ' (사본)',
    reuseTitle: '언제 다시 가시나요?',
    reuseBody: (n) => `같은 일정(${n}일)으로 새 여행을 만들어요. 동행·기록은 복사되지 않아요.`,
    reuseStart: '출발일',
    reuseCreate: '새 일정 만들기',

    emptyTitle: '아직 저장한 일정이 없어요',
    emptyBody: ['어디로 가고 싶은지만 말해 주세요.', 'AI 동행 티미가 일정 3개를 만들어 드릴게요.'],
    emptyChips: [
      { label: '혼자 도쿄 3박 4일', prompt: '혼자 도쿄 3박 4일 여행 일정 만들어줘' },
      { label: '주말 부산 1박', prompt: '주말에 부산 1박 2일 여행 일정 만들어줘' },
      { label: '처음 가는 유럽, 안전하게', prompt: '처음 가는 유럽 여행인데 혼자서도 안전한 일정으로 만들어줘' },
    ],
    emptyCta: '티미와 일정 만들기',
    emptyInvite: '초대 링크를 받으셨나요?',
    emptyInviteAction: '링크 붙여넣기',
    emptyInvitePlaceholder: 'tripmaker.tips/join/…',
    emptyInviteGo: '열기',
    emptyInviteInvalid: '초대 링크 형식이 아니에요',
    emptyFeed: '다른 여행자 일정 둘러보기',
    emptyFeedAction: '피드 →',
  },
  en: {
    title: 'My trips',
    newTrip: 'New trip',
    tabsLabel: 'Trip filter',
    tabUpcoming: (n) => `Upcoming ${n}`,
    tabPast: (n) => `Past ${n}`,
    loading: 'Loading your trips…',
    loginTitle: 'Sign in to keep your saved trips here',
    loginBody: 'You can plan without signing in. Sign in when you save.',
    login: 'Sign in',

    invite: (name, dest) => `${name} invited you to “${dest}”`,
    inviteView: 'View',

    nearest: 'Next up',
    undated: 'Dates not set',
    openTrip: 'Open trip',
    inviteCompanion: 'Invite',
    more: (title) => `More for ${title}`,
    readiness: 'Safety prep',
    nextTrips: 'After that',
    otherTrips: 'Other trips',
    createWithTimmy: 'Plan a new trip with Timmy',
    createWithTimmySub: 'Say where you want to go and get 3 plans',

    onTrip: (n) => `On your trip · Day ${n}`,
    dayProgress: (n, total) => `Day ${n} of ${total}`,
    nextPlace: 'Next stop',
    noPlaceToday: 'No stops planned for today',
    directions: (name) => `Directions to ${name}`,
    todayPlan: "Today's plan",
    safeMode: 'Safe mode',

    companions: { solo: 'Solo', withN: (n) => `${n} people` },
    places: (n) => `${n} places`,
    postTitle: (dest) => `How was ${dest}?`,
    postBody: 'Pick a few photos and Timmy will turn them into a travel diary.',
    writeDiary: 'Write a diary',
    shareFeed: 'Share to feed',
    shareFeedDone: 'Shared to the feed',
    postSafeNote: "Your trip is over, so it's safe to share now.",
    reuse: 'Go again with this plan',
    pastEmpty: 'No past trips yet',
    upcomingEmpty: 'No upcoming trips',

    menu: {
      open: 'Open map & plan',
      rename: 'Rename',
      renameSave: 'Save',
      renamePlaceholder: 'Trip name',
      invite: 'Invite companions',
      inviteSub: 'Send the link to plan together',
      shareLink: 'Create share link',
      shareLinkSub: 'Anyone can view the plan without signing in',
      duplicate: 'Duplicate as a new trip',
      remove: 'Delete trip',
      leave: 'Leave this trip',
      removeNote: "We'll ask once more before deleting.",
      leaveNote: "The trip stays for your companions.",
      confirmRemove: (title) => `Delete “${title}”? This can't be undone.`,
      confirmLeave: (title) => `Leave “${title}”?`,
      confirmYes: 'Delete',
      confirmLeaveYes: 'Leave',
      cancel: 'Cancel',
      close: 'Close',
    },
    toast: {
      renamed: 'Renamed',
      linkCopied: 'Link copied',
      duplicated: 'New trip created',
      removed: 'Trip deleted',
      left: 'You left the trip',
      failed: "Couldn't do that. Please try again shortly",
    },
    copySuffix: ' (copy)',
    reuseTitle: 'When are you going?',
    reuseBody: (n) => `We'll create a new trip with the same ${n}-day plan. Companions and notes aren't copied.`,
    reuseStart: 'Start date',
    reuseCreate: 'Create trip',

    emptyTitle: 'No saved trips yet',
    emptyBody: ['Just tell us where you want to go.', 'Timmy, your AI companion, will make 3 plans.'],
    emptyChips: [
      { label: 'Solo Tokyo, 4 days', prompt: 'Plan a 4-day solo trip to Tokyo' },
      { label: 'Weekend in Busan', prompt: 'Plan a 2-day weekend trip to Busan' },
      { label: 'First time in Europe, safely', prompt: "It's my first trip to Europe. Plan a safe itinerary for a solo traveler" },
    ],
    emptyCta: 'Plan with Timmy',
    emptyInvite: 'Got an invite link?',
    emptyInviteAction: 'Paste link',
    emptyInvitePlaceholder: 'tripmaker.tips/join/…',
    emptyInviteGo: 'Open',
    emptyInviteInvalid: "That doesn't look like an invite link",
    emptyFeed: "Browse other travelers' plans",
    emptyFeedAction: 'Feed →',
  },
};

export const getTripsCopy = (language) => tripsCopy[language] || tripsCopy.ko;
